### ISSUE TITLE
[VL] round result it not correct

### ISSUE THREAD

**Issue by liuyongvs** [apache/incubator-gluten#7323]
### Backend

VL (Velox)

### Bug description

spark-sql (default)> select round(44, -1);
40

while velox and gluten both return 44

### Spark version

None

**Comment by surnaik** [comment]
@liuyongvs Could you please provide the configs used, in my case it falls back to Spark

24/09/24 14:13:04 WARN ProjectExecTransformer: Validation failed with exception for plan: ProjectExecTransformer, due to: Not supported to map spark function name to substrait function name: toprettystring(round(44, -1), Some(America/Los_Angeles)), class name: ToPrettyString.
24/09/24 14:13:04 WARN GlutenFallbackReporter: Validation failed for plan: Project[QueryId=10], due to: Not supported to map spark function name to substrait function name: toprettystring(round(44, -1), Some(America/Los_Angeles)), class name: ToPrettyString..

**Comment by surnaik** [comment]
I investigated this issue, Spark casts Integral type to Decimal when scale < 0, hence it's output is 40, whereas we treat it as an integral type and return the same number - 44

**Comment by surnaik** [comment]
In Spark, we should always round negative decimals, which is different from Presto semantics. 

https://github.com/prestodb/presto/blob/7d9a0b0ae10a9e78b38d458cb0fafa04088b70d1/presto-main/src/main/java/com/facebook/presto/operator/scalar/MathFunctions.java#L1065
