### ISSUE TITLE
[VL] The example of Velox udf actually not running on native.

### ISSUE THREAD

**Issue by j7nhai** [apache/incubator-gluten#7760]
### Backend

VL (Velox)

### Bug description

Rewrite the class and package into a jar.

```
package org.apache.spark.sql.hive.execution;

import org.apache.hadoop.hive.ql.exec.UDF;

public class UDFStringString extends UDF {
  public String evaluate(String s1, String s2) {
    return s1 + " java " + s2;
  }
}
```

And run sql as following.

```
CREATE TEMPORARY FUNCTION hive_string_string AS 'org.apache.spark.sql.hive.execution.UDFStringString';

select hive_string_string("hello", "world");
explain select hive_string_string("hello", "world");

```

with conf
```
spark.gluten.sql.columnar.backend.velox.udfLibraryPaths=file:///root/libmyudf.so
```

And its output is:

```
hello java world
Time taken: 3.392 seconds, Fetched 2 row(s)

== Physical Plan ==
VeloxColumnarToRow
+- ^(2) ProjectExecTransformer [hello java world AS hive_string_string(hello, world)#16]
   +- ^(2) InputIteratorTransformer[fake_column#17]
      +- RowToVeloxColumnar
         +- *(1) Scan OneRowRelation[fake_column#17]

```

That means the udf is actually running on jvm because the output is "hello java world". But the plan show that it runs on native.

### Spark version

None

**Comment by FelixYBW** [comment]
It works on my side all the time. @marin-ma do we have a UT to check this?

**Comment by marin-ma** [comment]
@j7nhai Thanks for reporting this issue. The example provided in https://github.com/apache/incubator-gluten/blob/main/docs/developers/VeloxUDF.md cannot be offloaded. `hive_string_string("hello", "world")` is foldable because both inputs are constants, so the evaluation is done by Spark's optimizer rule `ConstantFolding` before Gluten can touch it. I will update the document with a proper example.

We do have the UT for velox udf and the input is a column. Please check https://github.com/apache/incubator-gluten/blob/main/backends-velox/src/test/scala/org/apache/gluten/expression/VeloxUdfSuite.scala#L163-L164
